# Generated by Django 4.2.6 on 2023-10-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_song_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mp3_file',
            field=models.FileField(upload_to='media/songs/'),
        ),
    ]
