# Generated by Django 4.2.6 on 2023-10-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_genre_alter_song_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('playlists', models.ManyToManyField(to='post.album')),
            ],
        ),
    ]
