# Generated by Django 4.2.6 on 2023-10-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
