# Generated by Django 4.2.6 on 2023-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='post.album'),
        ),
    ]
